---
- name: Instalar ufw
  apt: 
    name: ufw
    state: present

- name: Configuracion ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }

- name: Configuracion de reglas
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'limit', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
    - { rule: 'allow', port: '111', proto: 'tcp' }
    - { rule: 'allow', port: '2049', proto: 'tcp' }
    - { rule: 'allow', port: '111', proto: 'udp' }
    - { rule: 'allow', port: '2049', proto: 'udp' }

- name: Permitir acceso solo a IPs de estas redes
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 192.168.0.0/24    

- name: Activar logs
  ufw: 
    logging: 'on'
  notify:
    - reiniciar

- name: Activar firewall
  ufw: 
    state: enabled